name: Deploy via SSH (optional)

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'SSH host (e.g. 1.2.3.4)'
        required: true
      user:
        description: 'SSH user'
        required: true
      app_dir:
        description: 'Remote app directory'
        required: true
      jar_name:
        description: 'Jar filename on remote (e.g. app.jar)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR (no tests)
        run: |
          chmod +x gradlew
          ./gradlew bootJar -x test

      - name: Upload JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ github.event.inputs.host }}
          username: ${{ github.event.inputs.user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: ${{ github.event.inputs.app_dir }}

      - name: Restart service on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ github.event.inputs.host }}
          username: ${{ github.event.inputs.user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ${{ github.event.inputs.app_dir }}
            ls -l build/libs || true
            NEW_JAR=$(ls -t build/libs/*.jar | head -n 1)
            echo "Using $NEW_JAR"
            mkdir -p releases
            cp "$NEW_JAR" releases/${{ github.event.inputs.jar_name }}
            # 예: systemd 서비스 재시작 (서비스명은 환경에 맞게 수정)
            sudo systemctl daemon-reload || true
            sudo systemctl restart sejong-jokbo || true


